model:
  arch: minigpt_v2
  model_type: pretrain
  max_txt_len: 1024
  image_size: 448
  end_sym: "</s>"
  llama_model: "../../../mnt/nlpdata1/home/jprado/minigptv2/Llama-2-7b-chat-hf"
  ckpt: "../../../mnt/nlpdata1/home/jprado/minigptv2/checkpoints/checkpoint_stage2.pth"
  use_grad_checkpoint: True
  chat_template: True
  lora_r: 64
  lora_alpha: 16

datasets:
  flickr_grounded_caption:
    batch_size: 2
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 1


run:
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 8e-5
  min_lr: 1e-5
  warmup_lr: 1e-6

  weight_decay: 0.05
  max_epoch: 3
  num_workers: 6
  warmup_steps: 1000
  iters_per_epoch: 11196

  seed: 42
  output_dir: "checkpoints"

  amp: True
  resume_ckpt_path: null

  evaluate: False 
  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  wandb_log: True
  job_name: minigptv2_finetune
