model:
  arch: minigpt_v2
  model_type: pretrain
  max_txt_len: 500
  end_sym: "</s>"
  low_resource: False
  prompt_template: '[INST] {} [/INST]'
  llama_model: "../../../mnt/nlpdata1/home/jprado/minigptv2/Llama-2-7b-chat-hf"
  ckpt: "minigpt4/checkpoints/20231211151/checkpoint_2.pth"
  lora_r: 64
  lora_alpha: 16


datasets:
  cc_sbu_align:
    vis_processor:
      train:
        name: "blip2_image_eval"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"

evaluation_datasets:
  okvqa:
    eval_file_path: ../../../mnt/nlpdata1/home/jprado/LLaVA/playground/data/eval/
    img_path:   ../../../mnt/nlpdata1/home/jprado/LLaVA/playground/data/eval/    
    max_new_tokens: 50
    batch_size: 4

run:
  task: image_text_pretrain
  name: minigptv2_evaluation
  save_path: eval_results/

  

  

